app/views.py
from select import select
from unicodedata import category
from flask import Blueprint, Flask, flash, jsonify, redirect, render_template, request, jsonify, url_for
from flask_login import login_required, current_user
from .models import Info, User
from . import db


views = Blueprint('views', __name__)

# !home page


@views.route('/')
@login_required
def home():
    return render_template("home.html", user=current_user)

# !path data-selection page


@views.route('/database')
@login_required
def dataSelectionPath():
    return render_template("data_path_selection.html", user=current_user)


# !record table page


@views.route('/sector_table/', methods=['GET', 'POST'])
@login_required
def databaseTable():
    all_data = Info.query.all()
    return render_template('sector_table.html', user=current_user, all_data=all_data)


# !update record page


@ views.route('/update_data/<int:id>', methods=['GET', 'POST'])
@ login_required
def update_data(id):
    data = Info.query.get_or_404(id)
    if request.method == 'POST':
        # *from form
        sector_name = request.form.get('sectorName')
        sector_type = request.form.get('sectorType')
        population = float(request.form.get('population'))
        housing = float(request.form.get('housing'))
        income = request.form.get('income')
        amount_waste = float(request.form.get('amountWaste'))
        edit_date = request.form.get('editDate')
        # *from calculation
        amount_waste_kg = amount_waste*1000
        housingSize_result = population/housing
        wasteRate_result = amount_waste*1000/population

        data.sector_name = sector_name
        data.sector_type = sector_type
        data.population = population
        data.housing = housing
        data.income = income
        data.amount_waste = amount_waste
        data.edit_date = edit_date
        data.amount_waste_kg = amount_waste_kg
        data.housing_size = housingSize_result
        data.waste_rate = wasteRate_result

        db.session.add(data)
        db.session.commit()

        flash(
            f'ข้อมูลของ {sector_name} บนฐานข้อมูลถูกแก้ไข้แล้ว', category='success')
        return redirect(url_for('views.home'))
        # try:
        #     db.session.add()
        #     db.session.commit()
        #     flash(
        #         f'ข้อมูลของ {sector_name} บนฐานข้อมูลถูกแก้ไข้แล้ว', category='success')
        #     return redirect(url_for('views.home'))
        # except:
        #     flash(
        #         f'ข้อมูลของ {sector_name} แก้ไขไม่สำเร็จ', category='error')
        #     return render_template('update_date.html', user=current_user, data=data)
    return render_template('update_data.html', user=current_user, data=data)


# !create new data page


@views.route('/create_data', methods=['GET', 'POST'])
@login_required
def createData():
    if request.method == 'POST':
        # *from form
        zone = request.form.get('zone')
        sector_name = request.form.get('sectorName')
        sector_type = request.form.get('sectorType')
        lat = request.form.get('lat')
        lng = request.form.get('long')
        address = request.form.get('address')
        population = request.form.get('population')
        housing = request.form.get('housing')
        income = request.form.get('income')
        amount_waste = request.form.get('amountWaste')
        edit_date = request.form.get('editDate')
        # housing_size = request.form.get('housingSize')
        # waste_rate = request.form.get('wasteRate')

        sector = Info.query.filter_by(sector_name=sector_name).first()
        if sector:
            flash(f'ข้อมูลของ {sector_name} มีบนฐานข้อมูลแล้ว',
                  category='error')
        elif zone is None:
            flash('กรุณาระบุภาค', category='error')
        elif len(sector) < 1:
            flash('กรุณาระบุชื่อองค์กรบริหารส่วนท้องถิ่น', category='error')
        elif sector is None:
            flash('กรุณาระบุประเภทขององค์กรบริหารส่วนท้องถิ่น', category='error')
        elif lat is None:
            flash('กรุณาระบุพิกัดละติจูด', category='error')
        elif lng is None:
            flash('กรุณาระบุพิกัดลองติจูด', category='error')
        elif address is None:
            flash('กรุณาระบุที่อยู่', category='error')
        elif population < 1:
            flash('กรุณาระบจำนวนประชากร', category='error')
        elif housing < 1:
            flash('กรุณาระบจำนวนครัวเรือน', category='error')
        elif len(edit_date) < 1:
            flash('กรุณาระบุวันที่ทำการแก้ไขข้อมูล', category='error')
        else:
            # *from calculation
            amount_waste_kg = float(amount_waste)*1000
            housingSize_result = float(population)/float(housing)
            wasteRate_result = float(amount_waste)*1000/float(population)
            data = Info(zone=zone,
                        sector_name=sector_name,
                        sector_type=sector_type,
                        lat=lat,
                        long=lng,
                        address=address,
                        population=population,
                        housing=housing,
                        income=income,
                        housing_size=housingSize_result,
                        amount_waste=amount_waste,
                        amount_waste_kg=amount_waste_kg,
                        waste_rate=wasteRate_result,
                        edit_date=edit_date,
                        user_id=current_user.id,
                        )
            db.session.add(data)
            db.session.commit()
            flash(f'ข้อมูลของ {sector_name} ถูกเพิ่มบนฐานข้อมูลแล้ว',
                  category='success')
            return redirect(url_for('views.home'))
    return render_template("create_data.html", user=current_user)

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>
      {% block title
      %}การศึกษาปริมาณและองค์ประกอบของขยะมูลฝอยในชุมชนและสถานที่กำจัด{% endblock
      %}
    </title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">หน้าหลัก</a>
          <a class="nav-item nav-link" id="logout" href="/logout">ออกจากระบบ</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">เข้าสู่ระบบ</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">ลงทะเบียน</a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {%endif%} {% endfor %} {% endif %} {% endwith %}

    <div>{% block content%} {% endblock %}</div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/create_data.html
{% extends "base.html" %} {% block title %}การเพิ่มข้อมูลลงบนฐานข้อมูล{% endblock %} {% block content%}
<br>
<div class="text-center">
    <h2>การเพิ่มข้อมูลบนฐานข้อมูล</h2>
</div>
<Hr></Hr>
<br>
<form method="POST">
    <div class="container">
        <div class="form-group">
            <label for="zone">ภาค</label>
            <select name="zone" id="zone">
                <option value=" " disabled selected hidden>กรุณาเลือกภาค</option>
                <option value="ภาคเหนือ ">ภาคเหนือ</option>
                <option value="ภาคกลาง ">ภาคกลาง</option>
                <option value="ภาคตะวันออกเฉียงเหนือ ">ภาคตะวันออกเฉียงเหนือ</option>
                <option value="ภาคตะวันออก ">ภาคตะวันออก</option>
                <option value="ภาคใต้ ">ภาคใต้</option>
            </select>
        </div>
        <div class="form-group">
            <label for="sector_Name">ชื่อองค์กรปกครองส่วนท้องถิ่น (อปท.)</label>
            <input type="text" class="form-control " id="sectorName" name="sectorName" placeholder="กรุณาระบุชื่อองค์กรปกครองส่วนท้องถิ่น (อปท.) ">
        </div>
        <div class="form-group">
            <label for="sector_Type">ประเภทองค์กรปกครองส่วนท้องถิ่น (อปท.)</label>
            <select name="sectorType" id="sectorType">
                <option value=" " disabled selected hidden>กรุณาเลือกประเภทองค์กรปกครองส่วนท้องถิ่น (อปท.)</option>
                <option value="เขตการปกครองพิเศษ">เขตการปกครองพิเศษ</option>
                <option value="เทศบาลนคร (ทน.)">เทศบาลนคร (ทน.)</option>
                <option value="เทศบาลเมือง (ทม.)">เทศบาลเมือง (ทม.)</option>
                <option value="เทศบาลตำบล (ทต.)">เทศบาลตำบล (ทต.)</option>
                <option value="องค์การบริหารส่วนตำบล (อบต.)">องค์การบริหารส่วนตำบล (อบต.)</option>
            </select>
        </div>
        <div class="form-group">
            <label for="lat">พิกัดละติจูด</label>
            <input type="number" step="any" class="form-control " id="lat" name="lat" placeholder="กรุณาระบุละติจูด ">
            <label for="long">พิกัดลองติจูด</label>
            <input type="number" step="any" class="form-control " id="long" name="long" placeholder="กรุณาระบุลองติจูด ">
        </div>
        <div class="form-group">
            <label for="address">ที่อยู่</label>
            <input type="text" class="form-control " id="address" name="address" placeholder="กรุณาระบุที่อยู่ขององค์กรปกครองส่วนท้องถิ่น (อปท.) ">
        </div>
        <div class="form-group">
            <label for="population">จำนวนประชากร (คน)</label>
            <input type="number" step="any" class="form-control " id="population" name="population" placeholder="กรุณาระบุจำนวนประชากรเป็น ">
        </div>
        <div class="form-group">
            <label for="housing">จำนวนครัวเรือน (ครัวเรือน)</label>
            <input type="number" step="any" class="form-control " id="housing" name="housing" placeholder="กรุณาระบุจำนวนครัวเรือนในหน่วย ครัวเรือน ">
        </div>
        <div class="form-group">
            <label for="income">รายได้เฉลี่ยของประชากร (บาท/หัว/ปี)</label>
            <input type="number" step="any" class="form-control" id="income" name="income" placeholder="กรุณาระบุรายได้เฉลี่ยนของประชากรในหน่วย บาท/หัว/ปี ">
        </div>
        <div class="form-group">
            <label for="amount_Waste">ปริมาณขยะ (ตัน/วัน)</label>
            <input type="number" step="any" class="form-control" id="amountWaste" name="amountWaste" placeholder="กรุณาระบุปริมาณขยะในหน่วย ตัน/วัน ">
        </div>
        <div class="form-group">
            <label for="editDate">วันที่ทำการแก้ไขข้อมูล</label>
            <input type="date" id="editDate " name="editDate" >
        </div>
        <br>
        <div class="text-center ">
            <button type="submit " class="btn btn-primary ">ยืนยันเพื่อเพิ่มข้อมูล</button>
        </div>
    </div>
</form>
{% endblock %}

app/templates/data_path_selection.html
{% extends "base.html" %} {% block title
%}การเพิ่มข้อมูลและแก้ไขข้อมูลบนฐานข้อมูล{% endblock %} {% block content%} 
<br />
<div class='container'>
  <div class='page-header'>
  <h1 class="text-center">กรุณาเลือกรายการที่ต้องการทำ</h1>
</div>
</div>
<br />
<hr />
<h3 class="text-center">กรุณาเลือกรายการ</h3>
<br />
<div id="grid" class="row text-center">
  <div class="col-sm-6">
    <!-- search botton -->
    <div>
      <a id="searcH" href="{{url_for('views.databaseTable')}}">
        <button id="searchButton">
          <img src="static/map.png" alt="" width="100%" height="100%" />
        </button>
      </a>
    </div>
    <br />
    <div class="text-center">
      <a href="{{url_for('views.databaseTable')}}" class="btn btn-info" role="button">
        แก้ไขข้อมูลบนฐานข้อมูล
      </a>
    </div>
  </div>
  <div class="col-sm-6">
    <!-- information button -->
    <div>
      <a id="addData" href="/create_data">
        <button id="addDataButton">
          <img src="static/working.png" alt="" width="100%" height="100%" />
        </button>
      </a>
    </div>
    <br />
    <div class="text-center">
      <a href="/create_data" class="btn btn-info" role="buton">
        เพิ่มข้อมูลลงฐานข้อมูล
      </a>
    </div>
  </div>

  {% endblock %}
</div>

app/templates/home.html
{% extends "base.html" %} {% block title %}หน้าหลัก{% endblock %} {% block content%}
<div class="container text-center">
<div class="container text-center align-middle">
    <img src="static/nrct-logo.png" alt="nrct logo" width=15%" height="100%">
    <img src="static/hsm-logo.png" alt="hsm logo" width="15%" height="100%">
</div>
<br>
<div class="">
    <h1 align="center"><b>ยินดีต้อนรับ</b></h1>
    <h2 align="center"><b>การศึกษาปริมาณและองค์ประกอบของขยะมูลฝอยในชุมชนและสถานที่กำจัด</b></h2>
<h4 align="center">คุณ{{ user.first_name }} {{ user.last_name }} จากหน่วยงาน {{ user.sector }}</h4>
</div>
<br />
<hr />
<h3 align="center">กรุณาเลือกรายการ</h3>
<br />
<div id="grid" class="row text-center">
    <div class="col-sm-4">
        <!-- search botton -->
        <div>
            <a id="searcH" href="/search">
                <button id="searchButton">
          <img src="static/map.png" alt="search" width="50%" height="50%" />
        </button>
            </a>
        </div>
        <br />
        <div class="text-center">
            <a href="/search" class="btn btn-info" role="button">
               ฐานข้อมูลปริมาณขยะมูลฝอย
            </a>
        </div>
    </div>
    <div class="col-sm-4">
        <!-- information button -->
        <div>
            <a id="informaTion" href="/database">
                <button id="informationButton">
          <img src="static/working.png" alt="database" width="50%" height="50%" />
        </button>
            </a>
        </div>
        <br />
        <div class="text-center">
            <a href="/database"class="btn btn-info" role="button">
                เพิ่มและแก้ไขข้อมูลบนฐานข้อมูล
            </a>
        </div>
    </div>
    <div class="col-sm-4">
        <!-- prediction button -->
        <div>
            <a id="predicTion" href="/prediction/">
                <button id="predictionButton">
          <img
            src="static/predictive-chart.png"
            alt="waste prediction"
            width="50%"
            height="50%"
          />
        </button>
            </a>
        </div>
        <br />
        <div class="text-center">
            <a href="/prediction/" class="btn btn-info" role="button">
                การคาดการณ์ปริมาณขยะ
            </a>
        </div>
    </div>
</div>


{% endblock %}

app/templates/login.html
{% extends "base.html" %} {% block title %}เข้าสู่ระบบ{% endblock %} {% block content%}
<div class="container text-center">
    <img src="static/nrct-logo.png" alt="nrct logo">
    <img src="static/hsm-logo.png" alt="hsm logo">
</div>
<form method="POST">
    <div class="container">
        <br />
    <h3 align="center">เข้าสู่ระบบ</h3>
    <hr />
    <div class="form-group">
        <label for="email">อีเมล</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="กรุณาใส่อีเมลของคุณ" />
    </div>
    <div class="form-group">
        <label for="password">รหัสผ่าน</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="กรุณาใส่รหัสผ่านของคุณ" />
    </div>
    <br />
    <div class="text-center">
        <button type="submit" class="btn btn-primary">ยืนยันเพื่อเข้าสู่ระบบ</button>
        <br>
        <a href="/sign-up">ลงทะเบียนที่นี่</a>
    </div>
    </div>
</form>
{% endblock %}

app/templates/sector_table.html
{% extends "base.html" %} {% block title %}ข้อมูลทั้งหมดบนฐานข้อมูล{% endblock %} {% block content%}
<br />
<div class="text-center">
    <h2>ข้อมูลขององค์กรบริหารส่วนท้องถิ่น (อปท.) ทั้งหมด</h2>
</div>
<hr/>
<form method="POST">>
    <div class="">
        <table class="table">
            <tr>
                <th>ลำดับ</th>
                <th>ภาค</th>
                <th>ชื่อองค์กรบริหารส่วนท้องถิ่น</th>
                <th>ประเภทองค์กรบริหารส่วนท้องถิ่น</th>
                <th>ที่อยู่</th>
                <th>ประชากร (คน)</th>
                <th>จำนวนครัวเรือน (ครัวเรือน)</th>
                <th>รายได้เฉลี่ยนของประชากร (บาท/หัว/ปี)</th>
                <th>ขนาดครัวเรือน (คน/ครัวเรือน)</th>
                <th>ปริมาณขยะ (ตัน/วัน)</th>
                <th>อัตราการเกิดขยะ (กิโลกรัม/คน/วัน)</th>
            </tr>
            {% for data in all_data %}
            <tr>
                <td>{{ data.id }}</td>
                <input type="hidden" name="sector_id" value="{{ data.id }}">
                <td>{{ data.zone }}</td>
                <input type="hidden" name="zone" value="{{ data.zone }}">
                <td>
                    <a href="{{ url_for('views.update_data', id=data.id) }}">{{ data.sector_name }}</a>
                </td>
                <input type="hidden" name="sectorName" value="{{ data.sector_name }}">
                <td>{{ data.sector_type }}</td>
                <input type="hidden" name="sectorType" value="{{data.sector_type}}">
                <td>{{ data.address }}</td>
                <input type="hidden" name="address" value="{{ data.address }}">
                <td>{{ data.population }}</td>
                <input type="hidden" name="population" value="{{ data.population }}">
                <td>{{ data.housing }}</td>
                <input type="hidden" name="housing" value="{{data.housing}}">
                <td>{{ data.income }}</td>
                <input type="hidden" name="income" value="{{data.id}}">
                <td>{{ data.housing_size }}</td>
                <input type="hidden" name="housingSize" value="{{data.housing_size}}">
                <td>{{ data.amount_waste }}</td>
                <input type="hidden" name="amoutWaste" value="{{data.amount_waste}}">
                <td>{{ data.waste_rate }}</td>
                <input type="hidden" name="wasteRate" value="{{data.waste_rate}}">
            </tr>
            {% endfor %}
        </table>
    </div>
</form>
<br /> {% endblock %}

app/templates/sign_up.html
{% extends "base.html" %} {% block title %}ลงทะเบียน{% endblock %} {% block content%}
<div class="container text-center">
    <img src="static/nrct-logo.png" alt="nrct logo">
    <img src="static/hsm-logo.png" alt="hsm logo">
</div>
<form method="POST">
<div class="container">
    <br>
    <h3 align="center">ลงทะเบียน</h3>
    <hr>
    <br>
    <div class="form-group">
        <label for="email">อีเมล</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="กรุณาใส่อีเมล" />
    </div>
    <div class="form-group">
        <label for="firstName">ชื่อจริง</label>
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="กรุณาใส่ชื่อจริง" />
    </div>
    <div class="form-group">
        <label for="lastName">นามสกุล</label>
        <input type="text" class="form-control" id="lastName" name="lastName" placeholder="กรุณาใส่นามสกุล" />
    </div>
    <div class="form-group">
        <label for="sector">ชื่อหน่วยงาน</label>
        <input type="text" class="form-control" id="sector" name="sector" placeholder="กรุณาใส่ชื่อหน่วยงาน" />
    </div>
    <div class="form-group">
        <label for="password">รหัสผ่าน</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="กรุณาใส่รหัสผ่าน" />
    </div>
    <div class="form-group">
        <label for="confirmed_Password">ยืนยันรหัสผ่าน</label>
        <input type="password" class="form-control" id="confirmed_password" name="confirmed_Password" placeholder="กรุณายืนยันรหัสผ่าน" />
    </div>
    <br />
    <div class="text-center">
        <button type="submit" class="btn btn-primary">ยืนยันการลงทะเบียน</button>
    <br>
    <a href="/sign-up">
        <p>เข้าสู่ระบบที่นี่</p>
    </a>
    </div>
</div>
</form>
{% endblock %}

app/templates/update_data.html
{% extends "base.html" %} {% block title %}การแก้ไขข้อมูลบนฐานข้อมูล{% endblock %} {% block content%}
<br>
<div class="text-center">
    <h2>การแก้ไขข้อมูลบนฐานข้อมูล</h2>
</div>
<br>
<div class="text-center">
    <h4>คุณกำลังแก้ไขข้อมูลของ "{{data.sector_name}}"</h4>
</div>
<Hr></Hr>
<br>
<div class="container">
    <form action="#" method="POST">
    <div>
        <div>
            <h3>ข้อมูลที่แก้ไขได้</h3>
            <div class="form-group">
                <label for="sectorName">ชื่อขององค์กรบริหารส่วนท้องถิ่น (อปท.)</label>
                <input type="text" name="sectorName" id="sectorName" value="{{data.sector_name}}">
            </div>
            <div class="form-group">
                <label for="sector_Type">ประเภทองค์กรปกครองส่วนท้องถิ่น (อปท.)</label>
                <select name="sectorType" id="sectorType">
                <option value="" disabled selected hidden>กรุณาระบุประเภทองค์กรปกครองส่วนท้องถิ่น (อปท.)</option>
                <option value="เขตการปกครองพิเศษ">เขตการปกครองพิเศษ</option>
                <option value="เทศบาลนคร (ทน.)">เทศบาลนคร (ทน.)</option>
                <option value="เทศบาลเมือง (ทม.)">เทศบาลเมือง (ทม.)</option>
                <option value="เทศบาลตำบล (ทต.)">เทศบาลตำบล (ทต.)</option>
                <option value="องค์การบริหารส่วนตำบล (อบต.)">องค์การบริหารส่วนตำบล (อบต.)</option>
            </select>
            </div>
            <div>
                <label for="address">ที่อยู่:</label>
                <p>{{data.address}}</p>
            </div>
            <div class="form-group">
                <label for="population">จำนวนประชากร (คน) *เป็นจำนวนเต็ม</label>
                <input type="number" step="any" class="form-control " id="population" name="population" placeholder="กรุณาระบุจำนวนประชากรในหน่วย คน" value="{{data.population}}">
            </div>
            <div class="form-group">
                <label for="housing">จำนวนครัวเรือน (ครัวเรือน) *เป็นจำนวนเต็ม</label>
                <input type="number" step="any" class="form-control " id="housing" name="housing" placeholder="กรุณาระบุจำนวนครัวเรือนในหน่วย ครัวเรือน " value="{{data.housing}}">
            </div>
            <div class="form-group">
                <label for="income">รายได้เฉลี่ยของประชากร (บาท/หัว/ปี)</label>
                <input type="number" step="any" class="form-control" id="income" name="income" placeholder="กรุณาระบุรายได้เฉลี่ยนของประชากรในหน่วย บาท/หัว/ปี " value="{{data.income}}">
            </div>
            <div class="form-group">
                <label for="amount_Waste">ปริมาณขยะ (ตัน/วัน)</label>
                <input type="number" step="any" class="form-control" id="amountWaste" name="amountWaste" placeholder="กรุณาระบุปริมาณขยะในหน่วย ตัน/วัน" value="{{data.amount_waste}}">
            </div>
            <div class="form-group">
                <label for="editDate">วันที่ทำการแก้ไขข้อมูล</label>
                <input type="date" id="editDate " name="editDate">
            </div>
        </div>
        <br>
        <div class="text-center ">
            <button type="submit " class="btn btn-primary ">ยันยันการแก้ไขข้อมูล</button>
        </div>
    </div>
</form>
</div>
{% endblock %}